level_map = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXX                    XX                     XXXXXXXXXXX',
'XXXXXXXXXXX                    XX                     XXXXXXXXXXX',
'XXXXXXXXXXX                                           XXXXXXXXXXX',
'XXXXXXXXXXX                                           XXXXXXXXXXX',
'XXXXXXXXXXX                                           XXXXXXXXXXX',
'XXXXXXXXXXRP         OOO                              XXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  OO   XXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDDDXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX']
level_map2 = [
'XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXX              XXX                               XX      XX           XX                                                             XXXXXXXXXXXXX',
'XXXXXXXXXXXX             X                                 OXX      XX           XX                                                             XXXXXXXXXXXXX',
'XXXXXXXXXXXX             X                                XXXX      XX                                                                          XXXXXXXXXXXXX',
'XXXXXXXXXXXX             X                                XXXX      XXRBV           B                  B    VB                                  XXXXXXXXXXXXX',
'XXXXXXXXXXXX             XB         VB     XXXX  XXXX               XXXXXXXXXXXXXXXXX     O            XXXXXXX                                  XXXXXXXXXXXXX',
'XXXXXXXXXXXX     P       XXXXXXXXXXXXX                                                    XXXXXX                                                XXXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXX                                                                                                 O                          XXXXXXXXXXXXX',
'XXXXXXXXXXXX             B  V       B                                                                             XXXXXXX                       XXXXXXXXXXXXX',
'XXXXXXXXXXXX             XXXXXXXXXXXX                                                                     XXXX                                  XXXXXXXXXXXXX',
'XXXXXXXXXXXX O                                                                                 BV   B                                           XXXXXXXXXXXXX',
'XXXXXXXXXXXX X                                                   B       B             O       XXXXXX                                           XXXXXXXXXXXXX',
'XXXXXXXXXXXX                                                     XXXXXXXXX            XX                                                        XXXXXXXXXXXXX',
'XXXXXXXXXXXX                          XXXXXXXX                                                                                                  XXXXXXXXXXXXX',
'XXXXXXXXXXXX                    O                    XXXXXX                 XXXXXX                                                              XXXXXXXXXXXXX',
'XXXXXXXXXXXX                   XX                                                                                                               XXXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                                                    XXXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                                     X       X      XXXXXXXXXXXXX',
'XXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTXTTTTTTTXDDDXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXX']
level_map3 = [
'XXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                                            XXR     XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                               O                    XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                              XXX                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                         O       B   V B                                                          X XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                 XXXXXXX                                             XXX            XXXXXXXXXXXX',
'XXXXXXXXXXXX        P       XXX                                                                                                                 XXXXXXXXXXXX',
'XXXXXXXXXXXX       XXX                                                                                                B   V  B         XXXXXX   XXXXXXXXXXXX',
'XXXXXXXXXXXX                         O                          XXX     XXX                    XXXXXXX                XXXXXXXX                  XXXXXXXXXXXX',
'XXXXXXXXXXXX                        XXX                                                                        O                                XXXXXXXXXXXX',
'XXXXXXXXXXXX O                                     O      XXXX                                                XXX                               XXXXXXXXXXXX',
'XXXXXXXXXXXX X                                    XXX                                                                                           XXXXXXXXXXXX',
'XXXXXXXXXXXX                          B   V  B                          XXX             X      XXXXXXX                                          XXXXXXXXXXXX',
'XXXXXXXXXXXX                          XXXXXXXX                         XXXXX                                                                    XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                          XXXXXXX                                                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                                                    XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                                                    XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                     BV   B     B   VB                                                              XXXXXXXXXXXX',
'XXXXXXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXDDDDDXXXXXXTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX']
level_map4 = [
'XXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXX                                                                                                                       XXXXXXXXXXXX',
'XXXXXXXXXXXXR               BV       B        O                                                                                     XXXXXXXXXXXX',
'XXXXXXXXXXXXO                XXXXXXXXX    X  XXX    X                                                                               XXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXX     X                    O        X             X      X     X      X    X    X    B   VB                      XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                 XX                                         XXXXXX                      XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                         O              XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                        XXX             XXXXXXXXXXXX',
'XXXXXXXXXXXX                          XXXXX      XXXXX                                                                              XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                  XX                    XXXXXXXXXXXX',
'XXXXXXXXXXXX                                                                                                                        XXXXXXXXXXXX',
'XXXXXXXXXXXX                                               O                                           X                            XXXXXXXXXXXX',
'XXXXXXXXXXXXP                         XXXXX                X                                                                        XXXXXXXXXXXX',
'XXXXXXXXXXXXDDDXXXXX                                                                                                                XXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXX                                                                              XXXX                              XXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXX                                               BV        B                                                      XXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXX                  XXXXX                        XXXXXXXXXXX          XXXX                                        XXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXX      BV O  B                                                                                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXXTTTTTTXXXXXXXTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTXTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTXXXXXXXXXXXX',
'XXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX']
level_map5 = [
'XXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX       W                           XXXXXXXXXXXX',
'XXXXXXXXXXXX       XX      XXX   X             XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                         X         XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                     X             XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX                                   XXXXXXXXXXXX',
'XXXXXXXXXXXX  P                                XXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
]
tile_size = 40

screen_w = 900
screen_h = len(level_map)*tile_size
